[package]
name = "backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
sea-orm = { version = "0.12", features = [ "sqlx-postgres", "runtime-actix-native-tls", "macros" ] }
dotenvy = "0.15"
